version: '3'
services:

  mongo:
    container_name: db
    image: mongo:4.4.6
    ports:
      - "27017:27017"

  workplace:
    container_name: workplace
    build:
      context: workplace
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mongo
    networks:
      - my_network

  plant_shop:
    container_name: shop
    build: .
    ports:
      - "5000:5000"
    command: python app.py
    volumes:
      - .:/code
    networks:
      - my_network
    environment:
      - OTHER_SERVICE_URL=http://workplace:80

networks:
  my_network:
